SDKVERSION = 7.0
ARCHS = armv7 armv7s arm64

include theos/makefiles/common.mk

BUNDLE_NAME = RandomyToggle
RandomyToggle_FILES = Switch.xm
RandomyToggle_FRAMEWORKS = UIKit
RandomyToggle_LIBRARIES = flipswitch
RandomyToggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk